### ISSUE TITLE
[ Question/Doc ] Is it possible to do socket passing of fds? Any chance of a short demo?

### ISSUE THREAD

**Issue by ribasushi** [FGasper/p5-Linux-Perl#1]
I am **very** fuzzy on how the Perl/Libc interaction works at the level of this module, so I am not even sure what the proper argument construction would look like.

The gist of my question is: would it be possible to implement literally the API of [IO::FDPass](https://metacpan.org/pod/release/MLEHMANN/IO-FDPass-1.2/FDPass.pm#SYNOPSIS) or something similar to it, so that [the behavior in this test](https://metacpan.org/source/MLEHMANN/IO-FDPass-1.2/t/01_basic.t) would be achievable without XS/compilers?

Thanks in advance and sorry for the vague-ish question ;)

**Comment by FGasper** [comment]
That should be possible .. what are the underlying system calls? Try putting a “stat(‘————————-‘)” right before the send/recv commands then do strace -f on the test run; look for your stat to find the right place quickly.

-F

**Comment by ribasushi** [comment]
Yep, precisely. Was wondering if your module could somehow encapsulate this, would be pretty awesome ;)

**Comment by FGasper** [comment]
It would be inconsistent with the other functionality that L::P provides .. the other sub modules are kernel-level functionality.

What’s your stumbling block for creating such a module yourself? I’m indisposed right now, but it should be straightforward: get the ioctl constants from the Linux source tree (or strace maybe), then pack/unpack to work with the data structures. (pack() isn’t as hard to use as it seems .. look at uname() in L::P for an easy example.)

**Comment by ribasushi** [comment]
> It would be inconsistent with the other functionality that L::P provides

That's a very valid concern.

> What’s your stumbling block for creating such a module yourself?

Nothing beyond lack of time, and more importantly - not having been in the necessary headspace long enough that it will take me a while to research the corner cases which you already know intuitively :)

Nevertheless your first concern of the requested functionality not being a fit is sufficient to be a blocker, so I am closing this line of questions.

> I’m indisposed right now

Get better soon!
